const mongoose = require('mongoose');
const User = require('../models/User');
const Commodity = require('../models/Commodity');
const Material = require('../models/Material');
const { connectDB, disconnectDB } = require('../config/db');

const seedUsers = [
  {
    name: 'Dr. Rajesh Sharma (MoFPI Chief Technologist)',
    email: 'admin@mofpi.gov.in',
    password: 'Password@123',
    role: 'admin',
    organization: 'Ministry of Food Processing Industries (MoFPI) R&D Division',
  },
  {
    name: 'Priya Nair (Packaging Scientist)',
    email: 'priya@foodpack.org',
    password: 'Password@123',
    role: 'operator',
    organization: 'National Institute of Food Technology (NIFTEM)',
  },
];

const seedCommodities = [
  {
    name: 'Fresh Paneer (Cottage Cheese)',
    category: 'Dairy',
    subCategory: 'Fresh Cultured Dairy',
    baselineShelfLifeDays: 6,
    targetShelfLifeDays: 30,
    moistureSensitivity: 'High',
    oxygenSensitivity: 'Critical',
    lightSensitivity: 'Medium',
    temperatureSensitivity: 'Critical',
    optimalStorageTempMin: 0,
    optimalStorageTempMax: 4,
    respirationRate: 'None',
    storageCondition: 'Chilled (0-4°C)',
    fatOxidationRisk: 'High',
    targetMoistureContent: '52-58%',
    phRange: '5.6 - 6.0',
    description: 'High moisture traditional Indian dairy product prone to psychrotrophic bacterial spoilage and lipolytic rancidity under atmospheric oxygen.',
    tags: ['dairy', 'paneer', 'perishable', 'chilled', 'high-protein'],
    isPreset: true,
  },
  {
    name: 'Salem Turmeric Powder (GI Tagged)',
    category: 'Dry Foods & Spices',
    subCategory: 'Ground Spices',
    baselineShelfLifeDays: 90,
    targetShelfLifeDays: 365,
    moistureSensitivity: 'Critical',
    oxygenSensitivity: 'High',
    lightSensitivity: 'Critical',
    temperatureSensitivity: 'Low',
    optimalStorageTempMin: 15,
    optimalStorageTempMax: 28,
    respirationRate: 'None',
    storageCondition: 'Ambient (20-25°C)',
    fatOxidationRisk: 'Medium',
    targetMoistureContent: '< 10%',
    phRange: '6.0 - 6.8',
    description: 'High curcumin content (>4.5%) spice powder highly prone to photo-oxidation, aroma dissipation, and clumping at water activity > 0.60.',
    tags: ['spices', 'turmeric', 'hygroscopic', 'curcumin', 'light-sensitive'],
    isPreset: true,
  },
  {
    name: 'Alphonso Mangoes (Ratnagiri Fresh)',
    category: 'Fresh Produce',
    subCategory: 'Tropical Climacteric Fruit',
    baselineShelfLifeDays: 8,
    targetShelfLifeDays: 24,
    moistureSensitivity: 'Medium',
    oxygenSensitivity: 'Low',
    lightSensitivity: 'Low',
    temperatureSensitivity: 'High',
    optimalStorageTempMin: 10,
    optimalStorageTempMax: 13,
    respirationRate: 'High',
    storageCondition: 'Controlled Atmosphere (CA/MAP)',
    fatOxidationRisk: 'Low',
    targetMoistureContent: '82-86%',
    phRange: '4.0 - 4.5',
    description: 'Premium climacteric fruit with peak ethylene synthesis. Susceptible to chilling injury below 10°C and rapid ripening/decay in anaerobic environments.',
    tags: ['fresh-produce', 'mango', 'climacteric', 'respiration', 'export'],
    isPreset: true,
  },
  {
    name: 'Roasted Coorg Arabica Coffee Beans',
    category: 'Dry Foods & Spices',
    subCategory: 'Specialty Beverage Raw Material',
    baselineShelfLifeDays: 30,
    targetShelfLifeDays: 240,
    moistureSensitivity: 'High',
    oxygenSensitivity: 'Critical',
    lightSensitivity: 'High',
    temperatureSensitivity: 'Medium',
    optimalStorageTempMin: 15,
    optimalStorageTempMax: 22,
    respirationRate: 'None',
    storageCondition: 'Ambient (20-25°C)',
    fatOxidationRisk: 'Critical',
    targetMoistureContent: '2-4%',
    phRange: '4.8 - 5.3',
    description: 'Emits significant carbon dioxide (CO2) post-roasting while remaining intensely vulnerable to oxygen-induced staling and lipid rancidity.',
    tags: ['coffee', 'degassing', 'aroma-retention', 'oxygen-sensitive'],
    isPreset: true,
  },
  {
    name: 'Ready-to-Eat (RTE) Hyderabadi Biryani',
    category: 'Ready-to-Eat (RTE)',
    subCategory: 'Prepared Ambient Meal',
    baselineShelfLifeDays: 2,
    targetShelfLifeDays: 365,
    moistureSensitivity: 'High',
    oxygenSensitivity: 'Critical',
    lightSensitivity: 'High',
    temperatureSensitivity: 'High',
    optimalStorageTempMin: 15,
    optimalStorageTempMax: 30,
    respirationRate: 'None',
    storageCondition: 'Ambient (20-25°C)',
    fatOxidationRisk: 'Critical',
    targetMoistureContent: '55-62%',
    phRange: '5.8 - 6.2',
    description: 'Requires commercial sterilization (Retort F0 > 4.0) to achieve 12-month ambient shelf life without chemical preservatives.',
    tags: ['rte', 'retort', 'sterilized', 'ambient', 'convenience-food'],
    isPreset: true,
  },
  {
    name: 'Fresh Button Mushrooms (Agaricus)',
    category: 'Fresh Produce',
    subCategory: 'Cultivated Fungi',
    baselineShelfLifeDays: 4,
    targetShelfLifeDays: 14,
    moistureSensitivity: 'High',
    oxygenSensitivity: 'Medium',
    lightSensitivity: 'Low',
    temperatureSensitivity: 'Critical',
    optimalStorageTempMin: 1,
    optimalStorageTempMax: 4,
    respirationRate: 'Very High',
    storageCondition: 'Chilled (0-4°C)',
    fatOxidationRisk: 'Low',
    targetMoistureContent: '90-92%',
    phRange: '6.5 - 7.0',
    description: 'Extremely high respiration rate (200-300 mg CO2/kg·h). Rapid polyphenol oxidase browning and cap opening if gas balance is unmanaged.',
    tags: ['produce', 'mushrooms', 'high-respiration', 'antifog', 'chilled'],
    isPreset: true,
  },
  {
    name: 'Frozen Black Tiger Prawns (IQF)',
    category: 'Seafood',
    subCategory: 'Frozen Crustaceans',
    baselineShelfLifeDays: 45,
    targetShelfLifeDays: 365,
    moistureSensitivity: 'Critical',
    oxygenSensitivity: 'High',
    lightSensitivity: 'Medium',
    temperatureSensitivity: 'Critical',
    optimalStorageTempMin: -22,
    optimalStorageTempMax: -18,
    respirationRate: 'None',
    storageCondition: 'Frozen (-18°C)',
    fatOxidationRisk: 'High',
    targetMoistureContent: '75-80%',
    phRange: '6.8 - 7.2',
    description: 'Susceptible to freezer burn, ice crystal sublimation, melanosis (black spot enzymatic browning), and lipid oxidation.',
    tags: ['seafood', 'frozen', 'prawns', 'freezer-burn', 'puncture-resistant'],
    isPreset: true,
  },
  {
    name: 'Pure Desi A2 Cow Ghee',
    category: 'Oils & Fats',
    subCategory: 'Clarified Butterfat',
    baselineShelfLifeDays: 90,
    targetShelfLifeDays: 365,
    moistureSensitivity: 'High',
    oxygenSensitivity: 'Critical',
    lightSensitivity: 'Critical',
    temperatureSensitivity: 'Low',
    optimalStorageTempMin: 18,
    optimalStorageTempMax: 26,
    respirationRate: 'None',
    storageCondition: 'Ambient (20-25°C)',
    fatOxidationRisk: 'Critical',
    targetMoistureContent: '< 0.3%',
    phRange: '6.0 - 6.5',
    description: 'Nearly 100% lipid system prone to auto-oxidation, peroxide accumulation, and rancidity when exposed to UV light and oxygen.',
    tags: ['ghee', 'dairy-fat', 'light-shield', 'long-shelf-life'],
    isPreset: true,
  },
];

const seedMaterials = [
  {
    name: 'Multi-layer Aluminium Foil Retort Laminate (PET / Al / BOPA / CPP)',
    tradeName: 'RetortShield-4X Ultra',
    category: 'Metal & Aluminium Foil Laminate',
    description: 'Four-layer hermetic barrier laminate engineered for high-temperature retort sterilization (121°C) and multi-year ambient barrier.',
    oxygenBarrier: 'Superior (Zero OTR)',
    otrValue: 0.05,
    moistureBarrier: 'Superior (Zero WVTR)',
    wvtrValue: 0.05,
    lightBarrier: 'Total Opaque (100%)',
    lightTransmissionPercent: 0,
    minTemp: -30,
    maxTemp: 135,
    costIndex: 8,
    costPerKg: 380,
    recyclabilityScore: 3,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'None',
    punctureResistance: 'Ultra High',
    tensileStrengthMpa: 85,
    applications: ['Ready-to-Eat (RTE) meals', 'Retort biryani', 'Curries', 'Pasteurized sauces', 'MRE military rations'],
    sustainabilityNotes: 'Superior protection prevents food waste; requires specialized chemical delamination recycling plants.',
    isPreset: true,
  },
  {
    name: 'Co-extruded EVOH High-Barrier Vacuum Film (PA / EVOH / PE)',
    tradeName: 'OptiBarrier EVOH-9',
    category: 'High-Barrier Barrier Laminate',
    description: 'Co-extruded 9-layer barrier film with Ethylene Vinyl Alcohol (EVOH) core. Provides exceptional gas barrier and crystal-clear presentation.',
    oxygenBarrier: 'Excellent',
    otrValue: 1.2,
    moistureBarrier: 'Excellent',
    wvtrValue: 1.8,
    lightBarrier: 'Low (20-40%)',
    lightTransmissionPercent: 88,
    minTemp: -25,
    maxTemp: 95,
    costIndex: 6,
    costPerKg: 290,
    recyclabilityScore: 6,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'None',
    punctureResistance: 'High',
    tensileStrengthMpa: 65,
    applications: ['Fresh paneer vacuum pack', 'Cheese blocks', 'Smoked meats', 'MAP chilled poultry'],
    sustainabilityNotes: 'Halogen-free barrier; compatible with modern PE recycle streams when EVOH content is below 5%.',
    isPreset: true,
  },
  {
    name: 'Bio-Nanocomposite PLA High-Barrier Film (Bio-Flex Green)',
    tradeName: 'BioShield-Eco PLA',
    category: 'Biodegradable & Bio-polymers',
    description: 'Plant-derived Polylactic Acid (PLA) enhanced with cellulose nanocrystals for enhanced moisture and oxygen barrier properties.',
    oxygenBarrier: 'Good',
    otrValue: 8.5,
    moistureBarrier: 'Fair',
    wvtrValue: 6.2,
    lightBarrier: 'Moderate (40-70%)',
    lightTransmissionPercent: 45,
    minTemp: -10,
    maxTemp: 70,
    costIndex: 7,
    costPerKg: 340,
    recyclabilityScore: 9,
    compostable: true,
    biodegradationDays: 90,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'None',
    punctureResistance: 'Medium',
    tensileStrengthMpa: 48,
    applications: ['Organic dried spices', 'Artisanal bakery', 'Tea pouches', 'Confectionery wraps'],
    sustainabilityNotes: '100% bio-based from corn/sugarcane starch; certified industrial and soil compostable under ASTM D6400 / EN 13432.',
    isPreset: true,
  },
  {
    name: 'Micro-Perforated Antifog BOPP MAP Film',
    tradeName: 'FreshBreathe MAP-Pro',
    category: 'Active & MAP Smart Packaging',
    description: 'Laser-micro-perforated Biaxially Oriented Polypropylene with surfactant antifog coating for respiratory gas balance in fresh produce.',
    oxygenBarrier: 'Fair',
    otrValue: 1800,
    moistureBarrier: 'Good',
    wvtrValue: 4.5,
    lightBarrier: 'Transparent (0%)',
    lightTransmissionPercent: 92,
    minTemp: 0,
    maxTemp: 110,
    costIndex: 3,
    costPerKg: 165,
    recyclabilityScore: 9,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'Ethylene Absorber',
    punctureResistance: 'Medium',
    tensileStrengthMpa: 70,
    applications: ['Fresh mangoes', 'Button mushrooms', 'Strawberries', 'Fresh cut salad greens'],
    sustainabilityNotes: 'Mono-material Polypropylene (PP Category 5), 100% kerbside mechanically recyclable.',
    isPreset: true,
  },
  {
    name: 'Metallized Polyester / Polyethylene Pouch (VMPET / LLDPE)',
    tradeName: 'MetFlex LightGuard',
    category: 'High-Barrier Barrier Laminate',
    description: 'Vacuum-deposited aluminium layer on PET combined with linear low-density PE for superior light and moisture blocking at economical cost.',
    oxygenBarrier: 'Excellent',
    otrValue: 1.5,
    moistureBarrier: 'Excellent',
    wvtrValue: 0.9,
    lightBarrier: 'High (70-95%)',
    lightTransmissionPercent: 2,
    minTemp: -20,
    maxTemp: 90,
    costIndex: 4,
    costPerKg: 195,
    recyclabilityScore: 5,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'None',
    punctureResistance: 'High',
    tensileStrengthMpa: 60,
    applications: ['Turmeric & ground spices', 'Snack chips', 'Milk powder', 'Instant drink mixes'],
    sustainabilityNotes: 'Micro-thin metallized layer (<0.04μm) minimizes metal resource depletion vs thick solid foil.',
    isPreset: true,
  },
  {
    name: 'Amber Glass Container with Hermetic Lug Cap',
    tradeName: 'SilicaShield Amber-90',
    category: 'Glass & Hermetic Containers',
    description: 'Type-III soda-lime amber glass with total UV filtration and zero gas/moisture permeability.',
    oxygenBarrier: 'Superior (Zero OTR)',
    otrValue: 0.0,
    moistureBarrier: 'Superior (Zero WVTR)',
    wvtrValue: 0.0,
    lightBarrier: 'High (70-95%)',
    lightTransmissionPercent: 5,
    minTemp: -40,
    maxTemp: 180,
    costIndex: 6,
    costPerKg: 85,
    recyclabilityScore: 10,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'None',
    punctureResistance: 'Ultra High',
    tensileStrengthMpa: 120,
    applications: ['Desi cow ghee', 'Cold-pressed virgin edible oils', 'Honey', 'Liquid nutraceuticals'],
    sustainabilityNotes: 'Infinitely recyclable without quality loss; zero chemical leaching or microplastic migration.',
    isPreset: true,
  },
  {
    name: 'Active Scavenger Smart MAP Tray (PP / EVOH / Oxygen Scavenger)',
    tradeName: 'ActiveFresh ZeroOx Tray',
    category: 'Active & MAP Smart Packaging',
    description: 'Rigid thermoformed tray embedded with active iron-based oxygen scavengers and CO2 regulating pad for premium meat & dairy products.',
    oxygenBarrier: 'Superior (Zero OTR)',
    otrValue: 0.2,
    moistureBarrier: 'Excellent',
    wvtrValue: 1.1,
    lightBarrier: 'Low (20-40%)',
    lightTransmissionPercent: 75,
    minTemp: -20,
    maxTemp: 105,
    costIndex: 7,
    costPerKg: 310,
    recyclabilityScore: 7,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'Oxygen Scavenger',
    punctureResistance: 'High',
    tensileStrengthMpa: 55,
    applications: ['Fresh paneer cuts', 'Poultry breasts', 'Seafood fillets', 'Specialty pasta'],
    sustainabilityNotes: 'Active matrix actively absorbs headspace oxygen down to < 0.01% without chemical additives in food.',
    isPreset: true,
  },
  {
    name: 'Recycled rPET Mono-Material Tray with Peelable Lidding',
    tradeName: 'EcoLoop rPET-100',
    category: 'Rigid Plastic & Containers',
    description: '100% Post-Consumer Recycled polyethylene terephthalate (PCR-rPET) tray with certified super-clean decontamination process.',
    oxygenBarrier: 'Good',
    otrValue: 12.0,
    moistureBarrier: 'Good',
    wvtrValue: 8.0,
    lightBarrier: 'Transparent (0%)',
    lightTransmissionPercent: 90,
    minTemp: -30,
    maxTemp: 70,
    costIndex: 4,
    costPerKg: 180,
    recyclabilityScore: 10,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'None',
    punctureResistance: 'High',
    tensileStrengthMpa: 60,
    applications: ['Fresh berries', 'Peeled fruits', 'Bakery cookies', 'Confectionery'],
    sustainabilityNotes: 'Reduces carbon footprint by 65% compared to virgin PET; promotes circular closed-loop bottle-to-tray recycling.',
    isPreset: true,
  },
  {
    name: 'High-Density Polyethylene (HDPE) Heavy-Duty Barrier Pouch',
    tradeName: 'FreezeTough HDPE-80',
    category: 'Flexible Plastic (Polyolefins)',
    description: 'Co-extruded high-density polyethylene film engineered for cryogenic sub-zero durability and puncture resistance against sharp frozen seafood.',
    oxygenBarrier: 'Fair',
    otrValue: 85.0,
    moistureBarrier: 'Excellent',
    wvtrValue: 1.2,
    lightBarrier: 'Moderate (40-70%)',
    lightTransmissionPercent: 40,
    minTemp: -45,
    maxTemp: 110,
    costIndex: 3,
    costPerKg: 140,
    recyclabilityScore: 9,
    compostable: false,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'Moisture Absorber / Desiccant',
    punctureResistance: 'Ultra High',
    tensileStrengthMpa: 75,
    applications: ['Frozen IQF prawns', 'Frozen fish fillets', 'Bulk pulses', 'Grain storage'],
    sustainabilityNotes: 'Mono-material HDPE (Code 2), highly recyclable across all municipal waste recycling systems.',
    isPreset: true,
  },
  {
    name: 'Biodegradable Chitosan & Cellulose Bio-Coated Kraft Paper',
    tradeName: 'EarthKraft BioSeal',
    category: 'Paper & Coated Paperboard',
    description: 'Unbleached virgin Kraft paper coated with marine-derived chitosan bio-polymer and beeswax emulsion for water-resistant grease barrier.',
    oxygenBarrier: 'Good',
    otrValue: 22.0,
    moistureBarrier: 'Fair',
    wvtrValue: 14.0,
    lightBarrier: 'High (70-95%)',
    lightTransmissionPercent: 8,
    minTemp: -10,
    maxTemp: 90,
    costIndex: 5,
    costPerKg: 220,
    recyclabilityScore: 9,
    compostable: true,
    biodegradationDays: 45,
    fdaApproved: true,
    fssaiCompliant: true,
    activeScavengerType: 'Antimicrobial / Essential Oil Coating',
    punctureResistance: 'Medium',
    tensileStrengthMpa: 52,
    applications: ['Artisanal bread & bakery', 'Dry flour & grains', 'Loose tea leaves', 'Organic dry beans'],
    sustainabilityNotes: 'Naturally biodegradable in home compost within 45 days; zero plastic coating residue.',
    isPreset: true,
  },
];

const seedDatabase = async () => {
  try {
    console.log('[Seed] Clearing existing preset data...');
    await User.deleteMany({ email: { $in: seedUsers.map((u) => u.email) } });
    await Commodity.deleteMany({ isPreset: true });
    await Material.deleteMany({ isPreset: true });

    console.log('[Seed] Creating seed users...');
    for (const u of seedUsers) {
      await User.create(u);
    }

    const adminUser = await User.findOne({ email: 'admin@mofpi.gov.in' });

    console.log('[Seed] Inserting seed food commodities...');
    const commoditiesWithUser = seedCommodities.map((c) => ({
      ...c,
      createdBy: adminUser?._id,
    }));
    await Commodity.insertMany(commoditiesWithUser);

    console.log('[Seed] Inserting seed packaging materials...');
    const materialsWithUser = seedMaterials.map((m) => ({
      ...m,
      createdBy: adminUser?._id,
    }));
    await Material.insertMany(materialsWithUser);

    console.log(`[Seed] Successfully seeded:
- ${seedUsers.length} Users (Admin & Operator)
- ${seedCommodities.length} Food Commodities
- ${seedMaterials.length} Packaging Materials`);
  } catch (err) {
    console.error('[Seed] Error seeding database:', err.message);
  }
};

// If run directly via node seedData.js
if (require.main === module) {
  connectDB().then(() => {
    seedDatabase().then(() => {
      disconnectDB().then(() => process.exit(0));
    });
  });
}

module.exports = seedDatabase;
