import React, { useState } from 'react';
import { Download, FileText, Table, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function ExportPdfButton({ recommendation, filename = 'MoFPI_Packaging_Recommendation' }) {
  const [exporting, setExporting] = useState(false);
  const [dropdownOpen, setDropdownOpen] = useState(false);

  const exportPDF = () => {
    setExporting(true);
    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      const comm = recommendation.commoditySnapshot || {};

      // MoFPI Government Header
      doc.setFillColor(6, 78, 59); // mofpi-900
      doc.rect(0, 0, 210, 28, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('MINISTRY OF FOOD PROCESSING INDUSTRIES (MoFPI)', 14, 12);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text('AI-Based Intelligent Food Packaging Material Recommendation System', 14, 18);
      doc.text(`Report ID: REC-${recommendation._id?.substring(0, 8).toUpperCase() || 'REPORT'}  |  Date: ${new Date().toLocaleDateString()}`, 14, 24);

      // Section: Commodity Profile
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`1. Evaluated Food Commodity: ${comm.name || 'Commodity'}`, 14, 38);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const commodityInfo = [
        ['Category', comm.category || 'N/A', 'Storage Condition', comm.storageCondition || 'Ambient'],
        ['Baseline Shelf Life', `${comm.baselineShelfLifeDays || 'N/A'} Days`, 'Target Shelf Life', `${recommendation.targetShelfLifeDays || 'N/A'} Days`],
        ['Oxygen Sensitivity', comm.oxygenSensitivity || 'N/A', 'Moisture Sensitivity', comm.moistureSensitivity || 'N/A'],
        ['Light Sensitivity', comm.lightSensitivity || 'N/A', 'Respiration Rate', comm.respirationRate || 'None'],
      ];

      doc.autoTable({
        startY: 42,
        body: commodityInfo,
        theme: 'grid',
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [16, 185, 129] },
        margin: { left: 14, right: 14 },
      });

      // Section: Multi-Agent Recommended Materials Table
      let currentY = doc.lastAutoTable.finalY + 10;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('2. Ranked Packaging Materials (Multi-Agent AI Evaluation)', 14, currentY);

      const tableData = (recommendation.results || []).map((res) => [
        `#${res.rank}`,
        res.materialSnapshot?.name || 'Material',
        res.packagingFormat || 'High-Barrier Pouch',
        `${res.overallScore}/100`,
        `${res.barrierScore}/100`,
        `${res.estimatedShelfLifeDays} Days (${res.shelfLifeMultiplier}x)`,
        res.materialSnapshot?.compostable ? 'Yes (Compostable)' : `${res.materialSnapshot?.recyclabilityScore || 'N/A'}/10`,
      ]);

      doc.autoTable({
        startY: currentY + 4,
        head: [['Rank', 'Packaging Material', 'Format', 'Score', 'Barrier', 'Est. Shelf Life', 'Recyclability']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [6, 95, 70], textColor: [255, 255, 255], fontStyle: 'bold' },
        styles: { fontSize: 8, cellPadding: 3 },
        margin: { left: 14, right: 14 },
      });

      // Section: Top Ranked Scientific Justification
      if (recommendation.results && recommendation.results[0]) {
        const top = recommendation.results[0];
        let explainY = doc.lastAutoTable.finalY + 10;

        if (explainY > 240) {
          doc.addPage();
          explainY = 20;
        }

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(`3. Scientific Justification (Top Ranked: ${top.materialSnapshot?.name})`, 14, explainY);

        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'normal');
        const splitText = doc.splitTextToSize(top.aiExplanation || 'Recommended based on gas barrier matching and shelf life kinetics.', 182);
        doc.text(splitText, 14, explainY + 6);

        // Strengths & Weaknesses
        const strengthY = explainY + 6 + splitText.length * 4 + 4;
        doc.setFont('helvetica', 'bold');
        doc.text('Key Strengths: ', 14, strengthY);
        doc.setFont('helvetica', 'normal');
        doc.text((top.strengths || []).join('; ') || 'High barrier protection', 40, strengthY);
      }

      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`MoFPI Official Advisory Report  |  Page ${i} of ${pageCount}  |  Generated by FoodPack AI`, 14, 290);
      }

      doc.save(`${filename}_${comm.name ? comm.name.replace(/\s+/g, '_') : 'Report'}.pdf`);
    } catch (err) {
      console.error('PDF export failed:', err);
    } finally {
      setExporting(false);
      setDropdownOpen(false);
    }
  };

  const exportCSV = () => {
    try {
      const comm = recommendation.commoditySnapshot || {};
      const rows = [
        ['MoFPI AI Food Packaging Recommendation Report'],
        ['Commodity', comm.name || ''],
        ['Category', comm.category || ''],
        ['Baseline Shelf Life (Days)', comm.baselineShelfLifeDays || ''],
        ['Storage Condition', comm.storageCondition || ''],
        [''],
        ['Rank', 'Material Name', 'Category', 'Overall Score', 'Barrier Score', 'Cost Score', 'Sustainability Score', 'Predicted Shelf Life (Days)', 'Multiplier', 'Packaging Format', 'Compostable', 'FSSAI Compliant'],
      ];

      (recommendation.results || []).forEach((r) => {
        rows.push([
          r.rank,
          `"${r.materialSnapshot?.name || ''}"`,
          `"${r.materialSnapshot?.category || ''}"`,
          r.overallScore,
          r.barrierScore,
          r.costScore,
          r.sustainabilityScore,
          r.estimatedShelfLifeDays,
          `${r.shelfLifeMultiplier}x`,
          `"${r.packagingFormat || ''}"`,
          r.materialSnapshot?.compostable ? 'Yes' : 'No',
          'Yes',
        ]);
      });

      const csvContent = 'data:text/csv;charset=utf-8,' + rows.map((e) => e.join(',')).join('\n');
      const encodedUri = encodeURI(csvContent);
      const link = document.createElement('a');
      link.setAttribute('href', encodedUri);
      link.setAttribute('download', `${filename}.csv`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      console.error('CSV export failed:', err);
    } finally {
      setDropdownOpen(false);
    }
  };

  return (
    <div className="relative inline-block text-left">
      <button
        onClick={() => setDropdownOpen(!dropdownOpen)}
        disabled={exporting}
        className="inline-flex items-center space-x-2 px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-slate-950 font-semibold rounded-xl text-xs shadow-md shadow-emerald-600/20 transition active:scale-95 disabled:opacity-50"
      >
        {exporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
        <span>Export Report</span>
      </button>

      {dropdownOpen && (
        <div
          className="absolute right-0 mt-2 w-48 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 shadow-2xl p-1.5 z-50 animate-in fade-in zoom-in-95 duration-100 transition-colors"
          onClick={() => setDropdownOpen(false)}
        >
          <button
            onClick={exportPDF}
            className="w-full flex items-center space-x-2.5 px-3 py-2 text-xs text-slate-700 dark:text-slate-200 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition"
          >
            <FileText className="w-4 h-4 text-red-500 dark:text-red-400" />
            <span>Download PDF Report</span>
          </button>
          <button
            onClick={exportCSV}
            className="w-full flex items-center space-x-2.5 px-3 py-2 text-xs text-slate-700 dark:text-slate-200 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition"
          >
            <Table className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
            <span>Download CSV Data</span>
          </button>
        </div>
      )}
    </div>
  );
}
